services:
  spark-master:
    image: apache/spark:latest
    hostname: spark-master
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./volumes/spark/master:/opt/spark/work
    depends_on:
      - hadoop-namenode

  spark-worker-1:
    image: apache/spark:latest
    hostname: spark-worker-1
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_WEBUI_PORT: 8081
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./volumes/spark/worker-1:/opt/spark/work
    depends_on:
      - spark-master

  spark-worker-2:
    image: apache/spark:latest
    hostname: spark-worker-2
    container_name: spark-worker-2
    ports:
      - "8082:8082"
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_WEBUI_PORT: 8082
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./volumes/spark/worker-2:/opt/spark/work
    depends_on:
      - spark-master
